name: Terraform planning

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
      TF_VAR_service_account_key_file: ${{ secrets.YC_SERVICE_ACCOUNT_KEY_FILE }}
      TF_VAR_container_registry_id: ${{ secrets.YC_CONTAINER_REGISTRY_ID }}
      TF_VAR_hack_name: ${{ vars.HACK_NAME }}
      TF_VAR_hack_domain: ${{ vars.HACK_DOMAIN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        env:
          KEY: ${{ vars.HACK_NAME }}/terraform.tfstate
          BUCKET: ${{ secrets.YC_OBJECT_STORAGE_BUCKET }}
          ACCESS_KEY: ${{ secrets.YC_OBJECT_STORAGE_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.YC_OBJECT_STORAGE_SECRET_KEY }}
        run: |
          terraform init \
            -backend-config="key=$KEY" \
            -backend-config="bucket=$BUCKET" \
            -backend-config="access_key=$ACCESS_KEY" \
            -backend-config="secret_key=$SECRET_KEY"

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan
