name: Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
      TF_VAR_service_account_key_file: ${{ secrets.YC_SERVICE_ACCOUNT_KEY_FILE }}
      TF_VAR_hack_name: ${{ vars.HACK_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply
